import type { BlankItem, McItem, MtfItem, MultiItem, Section, SubjectData, TestSet } from "../../lib/types";

// Independently authored from docs/source/year-3-notes.txt, Modules 1–3 only.
// Situations test the lesson's reasoning, not recollection of the older bank's wording.
const mc = (q: string, a: string, distractors: string[], w: string, r: string): McItem => ({ q, a, o: [a, ...distractors], w, r });
const truth = (s: string, r: string): MtfItem => ({ s, t: true, r });
const falsehood = (s: string, replacement: string, r: string): MtfItem => ({ s, a: [replacement], d: replacement, r });
const multi = (q: string, a: string[], distractors: string[], w: string, r: string): MultiItem => ({ q, a, o: [...a, ...distractors], w, r });
const blank = (s: string, a: string, distractors: string[], w: string, r: string): BlankItem => ({ s, a, bank: [a, ...distractors], w, r });
type FreshBank = { tf: MtfItem[]; scenarios: McItem[]; multi: MultiItem[]; blanks: BlankItem[]; matching: Section };

export const freshBanks: Record<string, FreshBank> = {
  "module-1": {
    tf: [
      truth("A supplier's constraints can matter to EA even though the supplier is outside the enterprise.", "1.1 notes"),
      truth("A business-process model can omit irrelevant implementation detail and still be useful for EA.", "1.3 notes"),
      truth("A change in organizational culture can create alignment work even when the formal organization chart stays unchanged.", "1.2 notes"),
      falsehood("In the city-planning analogy, people who approve enterprise-wide priorities resemble <u>construction teams</u>.", "city governors", "1.3 notes"),
      falsehood("The organization-wide sharing of customer records concerns <u>process standardization</u>.", "data integration", "1.2 notes"),
      falsehood("An architect translating disagreements between business managers and developers is acting as an <u>auditor</u> between stakeholders.", "intermediary", "1.3 notes"),
    ],
    scenarios: [
      mc("A clinic documents how appointments work today and how remote appointments should work next year. Which additional element makes this a useful architectural roadmap rather than two disconnected snapshots?", "Goals and actions connecting the current and desired states", ["A promise to keep both states permanently unchanged", "A list of preferred hardware vendors only", "A diagram containing every employee's private information"], "EA connects the as-is state to the to-be state through goals and actions; mission, vision, and strategy provide context.", "1.2 notes"),
      mc("A wholesaler changes its software, but staff still exchange stock information through informal friendships rather than the official process. What should an alignment review include?", "Both formal procedures and informal working relationships", ["Only the server specifications", "Only the printed organization chart", "Only the software license cost"], "Organizational alignment involves hard and soft components. Informal culture can affect how the formal process actually operates.", "1.2 notes"),
      mc("A supplier's delivery platform cannot support a retailer's planned ordering process. The architect arranges a joint business, IT, and supplier discussion. Why is that appropriate?", "EA involves external actors and communication across stakeholder perspectives", ["Suppliers replace business executives in all EA decisions", "Architecture concerns only the retailer's internal hardware", "EA eliminates the need to understand business requirements"], "Third parties are major EA actors; architects act as intermediaries between diverse stakeholders.", "1.1 notes"),
      mc("An architect imports another company's entire framework without checking local priorities or capabilities. What is the most defensible response?", "Evaluate the framework's usefulness and fit for this organization before adopting it", ["Assume any widely used framework guarantees alignment", "Remove all business participation to simplify adoption", "Use the framework only to select one programming language"], "Framework adoption is not the goal of EA. Applicability, usefulness, and whether adoption is worthwhile must be considered.", "1.3 notes"),
      mc("A company is still serving customers while gradually replacing its warehouse systems. Which planning approach best fits the city analogy?", "Plan incremental changes while keeping ongoing operations viable", ["Design every future need perfectly before any change", "Treat the company as an empty construction site", "Assume architectural evolution has a fixed final endpoint"], "Cities and organizations run and evolve simultaneously; changes are incremental and evolution is ongoing.", "1.3 notes"),
      mc("A merger requires departments to share customer information, but they disagree on the meaning of 'active customer.' What should architects address before connecting the databases?", "A common, well-defined understanding of the shared concept", ["Identical screen colors across departments", "An agreement that each database must keep incompatible definitions", "A new vendor contract that avoids all stakeholder discussions"], "A common language helps integrate domains whose stakeholders have different concerns and terminology.", "1.3 notes"),
      mc("Executives ask architects to fix an unsuccessful expansion by producing more diagrams, while retaining the same poor decisions. Which limitation should the architects explain?", "EA artifacts cannot make incompetent decisions or actions competent", ["EA is useful only after a company stops operating", "Any diagram automatically improves business decisions", "EA should ignore executive decisions entirely"], "The notes explicitly warn that EA cannot transform incompetent decisions and actions merely through architectural work.", "1.1 notes"),
      mc("A company needs identical order-handling steps across branches but has not yet decided whether branches must share customer data. Which two dimensions must it discuss separately?", "Process standardization and data integration", ["Office size and software brand", "Architecture diagrams and employee headcount", "Financial profit and diagram color"], "An operating model reflects both integration and standardization requirements; specifying one does not automatically determine the other.", "1.2 notes"),
      mc("A new external reporting rule changes how a bank must manage information. What is the architectural significance of the trigger?", "An external driver may require changes to the EA practice and landscape", ["Only internal pressures can drive EA", "Regulations affect finance but can never affect architecture", "It proves the existing architecture must be replaced entirely overnight"], "External regulations can substantially affect organizations and trigger architectural work; complete overnight replacement is not implied.", "1.2 notes"),
      mc("Managers need to understand how departments interact, while developers need details about application dependencies. Why use several connected models?", "Different perspectives require abstractions that together capture the enterprise's essence", ["A single model is always sufficient for every concern", "Each model should contradict the others to show independence", "Models should include every detail regardless of audience"], "Multiple models are normally needed to communicate different domains while retaining an integrated view.", "1.3 notes"),
    ],
    multi: [
      multi("An enterprise reviews why its departments are poorly coordinated. Which are alignment components in Nadler's model?", ["Work", "People", "Formal organization", "Informal organization"], ["Diagram file format", "Processor brand"], "Nadler's alignment components are work, people, formal organization, and informal organization.", "1.2 notes"),
      multi("Which actions belong to an EA architect's responsibilities rather than merely producing a final diagram?", ["Maintaining the artifact repository", "Peer-reviewing EA artifacts", "Improving EA processes"], ["Guaranteeing perfect prediction of every future need", "Making stakeholder communication unnecessary"], "Architects manage artifacts, repositories, tools, and EA processes and serve as communicators.", "1.3 notes"),
      multi("Which observations fit the organization-as-city analogy?", ["Operations continue during evolution", "Poor planning can constrain later development", "Changes must account for multiple concerns"], ["The entire organization can be rebuilt instantly", "There is one best evolution path for every organization"], "The analogy emphasizes ongoing, incremental, multi-concern evolution rather than perfect or universal planning.", "1.3 notes"),
      multi("Which roles can legitimately contribute to EA discussions about a new business service?", ["Business unit managers", "IT executives", "External suppliers"], ["Only programmers, with all business actors excluded", "Only the owner of the diagramming software"], "The major actors include business executives/managers, IT executives/teams, architects, and third parties.", "1.1 notes"),
    ],
    blanks: [
      blank("A planning discussion about linking internal processes to external customers concerns ___ alignment.", "horizontal", ["vertical", "symbolic", "technical-only"], "Labovitz and Rosansky's horizontal alignment connects processes and customers; vertical alignment connects strategy and people.", "1.2 notes"),
      blank("When staff understand how their work supports top-level strategy, the discussion concerns ___ alignment.", "vertical", ["horizontal", "data-only", "symbolic"], "Vertical alignment connects strategy at the top with people throughout the organization.", "1.2 notes"),
      blank("A documented future state is the ___ state that architectural goals and actions aim toward.", "to-be", ["as-is", "informal", "ad hoc"], "The roadmap links the current as-is state to the desired to-be state.", "1.2 notes"),
    ],
    matching: { kind: "letter", title: "Fresh EA situations", inst: "Match each planning situation to the best concept.", items: [["Mission", "Explains why the organization exists"], ["Vision", "Describes where the organization wants to be"], ["Strategy", "Explains how the organization intends to get there"], ["Soft components", "Informal relationships and workplace culture"], ["Data integration", "How information is shared across business units"], ["Process standardization", "How similar business procedures should be across units"], ["Architect", "Intermediary who connects stakeholder perspectives and maintains EA artifacts"], ["External driver", "A pressure originating outside the organization"]] },
  },
  "module-2": {
    tf: [
      truth("Several projects can belong to one IT initiative when they share a unified purpose and business case.", "2.3 notes"),
      truth("Capability-based planning identifies what the business must be able to do before deciding how to implement it.", "2.1 notes"),
      truth("A measurable market-share target can still give IT planners insufficient implementation guidance.", "2.2 notes"),
      falsehood("A department proposes a solution to its own operational problem from the bottom up; this is a <u>fundamental</u> initiative.", "local", "2.3 notes"),
      falsehood("A plan to remove obsolete systems without adding business functionality is an <u>urgent</u> initiative.", "architectural", "2.3 notes"),
      falsehood("A concrete list of functional and non-functional behaviors for one information system is an <u>operating model</u>.", "business requirements", "2.2 notes"),
    ],
    scenarios: [
      mc("A hotel group insists on identical reservation procedures, but each hotel keeps an independent guest database. Which operating model best matches those stated requirements?", "Replication", ["Coordination", "Unification", "Diversification"], "Replication combines high process standardization with low data integration; the independent databases are the decisive integration clue.", "2.2 notes"),
      mc("An insurer shares customer data across its travel, health, and vehicle businesses, but their service processes differ. Which model fits?", "Coordination", ["Replication", "Unification", "Diversification"], "Coordination combines high data integration with low process standardization.", "2.2 notes"),
      mc("A holding company owns unrelated businesses with separate processes and separate information. Which model describes the stated arrangement?", "Diversification", ["Unification", "Replication", "Coordination"], "Diversification involves low integration and low standardization, allowing distinct businesses substantial autonomy.", "2.2 notes"),
      mc("A courier wants consistent dispatch procedures and shared shipment data across all branches. Which model fits both requirements?", "Unification", ["Replication", "Coordination", "Diversification"], "Unification requires high process standardization and high data integration.", "2.2 notes"),
      mc("Executives approve 'be the most trusted provider' as the only input to a new system design. Two teams interpret trust very differently. What is missing?", "An actionable middle ground connecting business concerns to IT decisions", ["A requirement to ignore business value", "Proof that broad strategy is always sufficient for detailed IT design", "A rule that all systems must use one vendor"], "Generic strategy can be ambiguous and offer little practical IT guidance; shared discussion points bridge business and IT.", "2.2 notes"),
      mc("A manufacturer first defines the ability to track customer behavior across channels, including people, knowledge, and processes, before choosing software. What is it identifying?", "A business capability", ["A detailed screen specification", "A single programming task", "An ITIL incident record"], "A capability is the general ability to perform a business activity and includes more than software alone.", "2.2 notes"),
      mc("A firm selects four initiatives for business value, then compares outsourcing and in-house delivery for each. Which pair of EA questions is being addressed?", "What initiatives to implement, and how to implement them", ["Which diagram colors to use, and who should print them", "Only the organization's financial perspective", "Only whether to certify its QMS"], "EA considers both the optimal initiatives portfolio and the optimal delivery approach.", "2.3 notes"),
      mc("A software team has improvised practices and wants to assess process maturity and identify practices for improving it. Which instrument is the most direct fit?", "CMMI", ["Business Model Canvas", "Balanced Scorecard", "Operating model quadrant"], "CMMI assesses software engineering process maturity and provides practices to increase it.", "2.1 notes"),
      mc("A support manager needs guidance on good IT service delivery and support, while auditors have already defined control objectives. Which complement best supplies the service-practice guidance?", "ITIL", ["Business Model Canvas", "A future-state vision statement", "Capability-based planning alone"], "COBIT states control objectives; ITIL complements it with service-delivery and support practices.", "2.1 notes"),
      mc("An executive's new market strategy requires a specialized platform. Architects note it may become an isolated legacy system if priorities change. What type of initiative and risk are illustrated?", "Strategic initiative with a risk of becoming legacy after the strategy changes", ["Architectural initiative that never adds business functionality", "Fundamental initiative guaranteed to outlive every business change", "Urgent initiative caused only by an unforeseen regulation"], "Strategic initiatives stem from current business strategy and carry the caveat that they may become legacy after that strategy.", "2.3 notes"),
    ],
    multi: [
      multi("A team builds an IT initiative proposal. Which details belong among its attributes?", ["Core business problem", "Business sponsors", "Scope", "Business case and financial details"], ["Only the diagram's typography", "A guarantee that business strategy never changes"], "The initiative's attributes include needs, objectives, scope, business case, sponsors, and budget.", "2.3 notes"),
      multi("Which are Balanced Scorecard perspectives rather than operating-model quadrants?", ["Customer", "Learning and growth", "Internal business processes", "Financial"], ["Replication", "Coordination"], "The BSC has four perspectives: financial, customer, internal business processes, and learning and growth.", "2.1 notes"),
      multi("Which factors explain why business strategy alone may be a weak basis for detailed IT planning?", ["Ambiguous generic statements", "Frequent changes in priorities", "Little practical implementation guidance"], ["All strategies already specify every system requirement", "Strategy always guarantees reusable IT components"], "The notes identify vagueness, insufficient direction, instability, and non-reusable short-term systems as problems.", "2.2 notes"),
      multi("Which proposed changes fit architectural initiatives when no new business functionality is being added?", ["Retiring obsolete legacy systems", "Upgrading obsolete hardware to improve the IT landscape"], ["Launching a new service solely for this year's market strategy", "Fixing a department's new sales-report requirement"], "Architectural initiatives improve the IT landscape; the lesson's examples include obsolete hardware upgrades and legacy-system decommissioning.", "2.3 notes"),
    ],
    blanks: [
      blank("A quality-management system documents and controls how processes are performed; the standard discussed for this is ___.", "ISO 9001", ["ITIL", "Business Model Canvas", "CMMI"], "ISO 9001 sets criteria for a QMS, including process identification and documentation to which EA can contribute.", "2.1 notes"),
      blank("An unanticipated government rule requires immediate system changes; the initiative is classified as ___.", "urgent", ["architectural", "local", "fundamental"], "Urgent initiatives arise from unanticipated business needs, often triggered by the external environment.", "2.3 notes"),
      blank("A model that benchmarks organizational performance against best practices and supports continuous improvement is ___.", "EFQM", ["CMMI", "ITIL", "Business Model Canvas"], "EFQM assesses broader organizational excellence and supports learning, innovation, and improvement.", "2.1 notes"),
    ],
    matching: { kind: "letter", title: "Fresh business–IT decisions", inst: "Match each business–IT situation to its best discussion point or initiative type.", items: [["Operating model", "Deciding organization-wide integration and standardization requirements"], ["Business capability", "Defining the general ability to serve customers across channels"], ["Specific business need", "Seeking an improvement in employee-hours tracking accuracy"], ["Business process", "Describing actors, steps, inputs, and outputs in approval work"], ["Business requirements", "Specifying functional and non-functional system behavior"], ["Strategic initiative", "Delivering a solution tied to the current market strategy"], ["Urgent initiative", "Responding to an unforeseen critical operational problem"], ["Architectural initiative", "Improving the IT landscape without new business functionality"]] },
  },
  "module-3": {
    tf: [
      truth("Changing the presentation of a model need not change the architectural meaning it represents.", "3.2 notes"),
      truth("A stakeholder group can be treated as a stakeholder, not only each individual person.", "3.2 notes"),
      truth("Change analysis should consider dependencies across architectural domains rather than only the altered component.", "3.1 notes"),
      falsehood("The perspective that determines which architectural elements are visible is a <u>view</u>.", "viewpoint", "3.2 notes"),
      falsehood("The tangible collection of models and text representing architectural understanding is the architectural <u>conception</u>.", "description", "3.2 notes"),
      falsehood("Decomposing a system into parts while also considering relationships among those parts is called <u>visualization</u>.", "compositionality", "3.1 notes"),
    ],
    scenarios: [
      mc("A hospital changes its patient-identity rules. Architects check affected data structures, applications, and clinical workflows. Which lifecycle support is most directly illustrated?", "Assessing cross-domain consequences during change", ["Ignoring all domains except the data domain", "Replacing stakeholder views with one decorative image", "Choosing a notation solely by its colors"], "A change in one architecture may affect others; architects need support for evaluating consequences across domains.", "3.1 notes"),
      mc("The same booking service is shown as a flowchart for operations staff and a technical notation for developers. Both representations retain the same dependencies. What remains consistent?", "Architectural content and semantics despite different visualization", ["The stakeholder groups' professional backgrounds", "Every graphical symbol and layout", "The requirement that architecture changes whenever the font changes"], "Content and visualization are distinct; architecture should be independent of visualization while shared meaning stays consistent.", "3.2 notes"),
      mc("A process team uses BPMN while a software team uses UML. Both models are valid, but corresponding elements cannot simply be paired one-for-one. What challenge is this?", "Integration across different modeling languages and stakeholder concerns", ["Proof that both models must be discarded", "A lack of any need for common vocabulary", "A financial-measurement problem only"], "Different standards, languages, and stakeholder views make one-to-one cross-domain mapping difficult.", "3.1 notes"),
      mc("A manager knows how a company operates but has never documented that understanding. An architect later captures it in models and text. What transition occurred?", "Architectural conception was represented in an architecture description", ["A viewpoint was converted into an operating model quadrant", "Architecture became identical to a software vendor", "Business requirements became financial measures"], "Conception is the stakeholder's intangible understanding; description is its tangible representation through artifacts.", "3.2 notes"),
      mc("A service manager wants service dependencies, while a security officer wants access relationships. What should determine the subset shown to each?", "A viewpoint reflecting each stakeholder's concerns", ["A rule that every stakeholder must see every detail", "The accidental order in which diagrams were saved", "Only the architect's favorite illustration style"], "Specific views are specified through viewpoints, and visible elements depend on stakeholder concerns.", "3.2 notes"),
      mc("A diagram uses attractive icons, but viewers disagree on what the arrows mean. Why is its visual appeal insufficient?", "A model needs defined, unambiguous meaning, not merely a picture", ["Any attractive picture necessarily has formal semantics", "Formal meaning is useful only when there are no stakeholders", "Architecture is the number of symbols on the page"], "Pictures may support multiple interpretations; a model uses a formalized language and unambiguous conception.", "3.2 notes"),
      mc("Architects choose domains by examining stakeholders, priority areas, organizational strengths, and the ease of linking the domains. Why not automatically copy another company's list?", "Domain choice should fit the organization's concerns and integration needs", ["Domains can never differ between organizations", "Only one universally mandatory list exists", "Integration is unnecessary after domains are named"], "The lesson recommends examining stakeholders, priorities, capabilities, flexibility, and integration when choosing domains.", "3.1 notes"),
      mc("A team moves from high-level architecture into implementation, but its detailed design tool cannot connect to the original models. Which realization support is missing?", "Seamless movement between detail levels and integration between design tools", ["More unrelated pictures without model connections", "A promise never to use detailed designs", "A complete removal of business-process context"], "Realization requires more detailed design, seamless transitioning between levels, and integration of design tools.", "3.1 notes"),
      mc("One model describes software components; another describes application functions. Architects investigate how components support functions. Which integration problem are they addressing?", "Connecting structural and behavioral models", ["Choosing between replication and diversification", "Replacing quality management with market strategy", "Classifying a government's unexpected regulation"], "The lesson identifies integrating structure and behavior as a distinct challenge; software components versus application functions is an example.", "3.1 notes"),
      mc("A formal architecture notation is hard for nontechnical managers to interpret. Architects explain the real-world meaning of the symbols. What is that explanation emphasizing?", "The semantic interpretation of the symbolic model", ["A change to the organization's operating model", "The assumption that symbols alone guarantee understanding", "A requirement that every manager learn every technical notation first"], "Symbolic models use notation referring to reality; semantic models express an interpretation, important for stakeholder understanding.", "3.2 notes"),
    ],
    multi: [
      multi("Which questions are relevant when choosing architectural domains?", ["Which stakeholders and concerns matter?", "Which organizational areas are priorities?", "How easily can the chosen domains be integrated?"], ["How can every stakeholder concern be excluded?", "Which diagram color guarantees business success?"], "Domain selection considers stakeholders, priorities, capabilities, approach flexibility, and ease of integration.", "3.1 notes"),
      multi("During architecture communication, which support helps stakeholders understand what matters to them?", ["Filtering information for the audience", "Showing relevant aspects", "Emphasizing connections between domains"], ["Displaying all implementation details to every audience", "Hiding every dependency between domains"], "Communication requires relevant views, information filtering, and emphasis on cross-domain relationships.", "3.1 notes"),
      multi("Which statements correctly distinguish architecture understanding and representation?", ["Conception can exist before it is documented", "Architecture description can use models and text", "Stakeholder concerns influence conception"], ["Conception exists only after a diagram is printed", "A description must capture every concern in a single universal model"], "Conception is intangible understanding shaped by perspective; description represents it in tangible artifacts.", "3.2 notes"),
      multi("Which practices support an integrated architectural model collection?", ["Keeping shared concepts consistent across views", "Examining relationships between partial models", "Using common, well-defined vocabulary"], ["Giving a shared concept incompatible meanings without explanation", "Treating every domain as having no dependencies"], "Multiple partial models form a collective whole; shared vocabulary, meaning, and relationships help integrate them.", "3.1 and 3.2 notes"),
    ],
    blanks: [
      blank("An arrow has a precise meaning agreed in the modeling language; that inherent meaning is its ___.", "semantics", ["visual decoration", "operating model", "budget"], "Architecture semantics concerns inherent meaning; visualization concerns how content is presented.", "3.2 notes"),
      blank("The actual elements shown from a stakeholder's selected perspective form the ___.", "view", ["viewpoint", "initiative portfolio", "business case"], "A viewpoint defines the perspective; a view is what is seen from it.", "3.2 notes"),
      blank("The act of abstracting a representation from part of the enterprise using a language and medium is ___.", "modeling", ["certification", "outsourcing", "benchmarking"], "Modeling abstracts a model from part of the universe using language and a medium.", "3.2 notes"),
    ],
    matching: { kind: "letter", title: "Fresh architecture interpretation", inst: "Match each modeling situation to the concept it illustrates.", items: [["Conception", "A stakeholder's undocumented understanding of the enterprise"], ["Description", "Tangible models and text representing architectural understanding"], ["Viewpoint", "The perspective selecting what matters to a stakeholder"], ["View", "The elements visible from that selected perspective"], ["Content", "The architectural concepts included in a model"], ["Visualization", "How those concepts are presented"], ["Compositionality", "Understanding parts and the relationships among them"], ["Semantics", "The inherent meaning represented by model elements"]] },
  },
};

/** Append, never replace: saved runs retain their questions and earlier banks retain their IDs. */
export function expandQuestionData(data: SubjectData): SubjectData {
  const tests = { ...data.tests }, pools = { ...data.pools }, scenarios = { ...data.scenarios }, multi = { ...data.multi }, blanks = { ...data.blanks };
  for (const [slug, bank] of Object.entries(freshBanks)) {
    const module = `M${slug.slice(-1)}`;
    const mtf = bank.tf.map(q => ({ ...q, m: module }));
    const set: TestSet = { desc: "Fresh application questions", mtf, secs: [{ kind: "mc", title: "Fresh case scenarios", inst: "Choose the best answer using the lesson concepts.", items: bank.scenarios }, bank.matching] };
    tests[slug] = { ...tests[slug], fresh: set };
    pools[module] = [...(pools[module] ?? []), ...mtf];
    scenarios[module] = [...(scenarios[module] ?? []), ...bank.scenarios];
    multi[slug] = [...(multi[slug] ?? []), ...bank.multi];
    blanks[slug] = [...(blanks[slug] ?? []), ...bank.blanks];
  }
  return { ...data, tests, pools, scenarios, multi, blanks };
}
